frameworkVersion: "1.78.1"
service: ebased-examples

plugins:
  - serverless-iam-roles-per-function
  
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    project: ebased-examples
  tracing:
    lambda: true
    apiGateway: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
  environment:
    NODE_ENV: ${self:provider.stage}
    LOG_LEVEL: INFO

custom:
  stackPrefix: '${self:service}-${self:provider.stage}'

functions:
  - ${file(src/exchange/index.yml)}
  - ${file(src/account/index.yml)}
  - ${file(src/wallet/index.yml)}

resources:
  - ${file(resource/exchange/topic.yml)}
  - ${file(resource/account/queue.yml)}