Resources:
  
  CreateDepositQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${file(resource/index.json):account.createDepositQueue}
      
  CreateWithdrawalQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${file(resource/index.json):account.createWithdrawalQueue}
  CreateWithdrawalQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument: 
        Statement:
          Effect: Allow
          Principal: '*'
          Action: 
            - SQS:*
          Resource: !GetAtt CreateWithdrawalQueue.Arn
      Queues: 
        - !Ref CreateWithdrawalQueue